openapi: 3.0.3
info:
  title: Library API
  version: 1.4.2
  description: STD22079

servers:
  - url: https://library.com

tags:
  - name: Books
    description: Concerns books
  - name: Authors
    description: Concerns authors
  - name: Topics
    description: Concerns topics

paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: Get a list of all books ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter books by name
          required: false
          schema:
            type: string
        - in: query
          name: releaseDateMin
          description: Minimum release date. Ignored if `releaseDateMax` is not provided. Must not be after `releaseDateMax`.
          schema:
            type: string
            format: date
          required: false
        - in: query
          name: releaseDateMax
          description: Maximum release date. Ignored if `releaseDateMin` is not provided. Must not be before `releaseDateMin`.
          schema:
            type: string
            format: date
          required: false
        - in: query
          name: page
          description: "Page number for pagination (default: 1)"
          required: false
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          description: "Number of items per page (default: 50)"
          required: false
          schema:
            type: integer
            default: 50
      responses:
        200:
          description: List of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    put:
      tags:
        - Books
      summary: Create or update a list of books
      description: Create or update a list of books.
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CrupdateBook'
      responses:
        200:
          description: List of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    delete:
      tags:
        - Books
      summary: Delete a Book
      description: Delete a book by its ID.
      operationId: deleteBook
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Delete successful

  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - Books
      operationId: modifyAuthorOfBook
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
        - name: authorId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Author successfully modified in the book
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /books/authors:
    put:
      tags:
        - Books
      operationId: modifyAuthorOfBookList
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateBookAuthor'
      responses:
        200:
          description: Authors successfully modified in the list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /books/{bookId}/topics/{topicId}:
    put:
      tags:
        - Books
        - Topics
      operationId: modifyTopicOfBook
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
        - name: topicId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Topic successfully modified in the book
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /books/topics:
    put:
      tags:
        - Books
        - Topics
      operationId: modifyListOfTopicsInABook
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateBookTopic'
      responses:
        200:
          description: Topics successfully modified in the list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /topics:
    get:
      tags:
        - Topics
      summary: Get all topics
      description: Get a list of all topics ordered by updated datetime.
      operationId: getTopics
      parameters:
        - in: query
          name: page
          description: "Page number for pagination (default: 1)"
          required: false
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          description: "Number of items per page (default: 50)"
          required: false
          schema:
            type: integer
            default: 50
      responses:
        200:
          description: List of filtered topics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'

    put:
      tags:
        - Topics
      summary: Create or update a list of topics
      description: Create or update a list of topics.
      operationId: crupdateTopics
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Topic'
      responses:
        200:
          description: List of created or updated topics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'

    delete:
      tags:
        - Topics
      summary: Delete a Topic
      description: Delete a topic by its ID.
      operationId: deleteTopic
      parameters:
        - name: topicId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Delete successful

  /authorTopics:
    get:
      tags:
        - Topics
        - Authors
      summary: Get all topics of an author
      description: Get topics of an author ordered by updated datetime.
      operationId: getAuthorTopics
      parameters:
        - name: authorId
          in: query
          description: Author ID to filter topics.
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of filtered topics of a given author
          content:
            application/json:
              schema:
                type: object
                properties:
                  author:
                    $ref: '#/components/schemas/Author'
                  topics:
                    type: array
                    items:
                      $ref: '#/components/schemas/Topic'

  /authors:
    get:
      tags:
        - Authors
      summary: Get all authors
      description: Get a list of all authors ordered by their name ascending.
      operationId: getAuthors
      parameters:
        - name: authorName
          in: query
          description: Filter authors by name.
          required: false
          schema:
            type: string
        - in: query
          name: page
          description: "Page number for pagination (default: 1)"
          required: false
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          description: "Number of items per page (default: 50)"
          required: false
          schema:
            type: integer
            default: 50
      responses:
        200:
          description: List of returned authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'

    put:
      tags:
        - Authors
      summary: Create or update an author
      description: Create or update an author.
      operationId: updateAuthor
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          description: List of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'

    delete:
      tags:
        - Authors
      summary: Delete an Author
      description: Delete an author by its ID.
      operationId: deleteAuthor
      parameters:
        - name: authorId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Delete successful

components:
  schemas:
    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
        authorId:
          type: string
      required:
        - "bookId"
        - "authorId"

    CrupdateBook:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: string
        releaseDate:
          type: string
          format: date

    UpdateBookTopic:
      type: object
      properties:
        bookId:
          type: string
        topicId:
          type: string
      required:
        - "bookId"
        - "topicId"

    Topic:
      type: object
      properties:
        id:
          type: string
        topic:
          type: string
      enum:
        - ROMANCE
        - COMEDY
        - OTHER

    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
      enum:
        - M
        - F

    Book:
      type: object
      allOf:
        - $ref: "#/components/schemas/CrupdateBook"
      properties:
        author:
          $ref: "#/components/schemas/Author"
        topic:
          $ref: "#/components/schemas/Topic"
